### PR TITLE
Conditional backup report generation

### PR DESCRIPTION
**Pull request by Danp2**

### CODE REVIEW

**Comment by julien-f** [comment]
You know, you don't have to close the PR, you can just push new commits and it will be updated automatically.

**Comment by Danp2** [comment]
Thanks. I was actually trying to "fix" things where the top two merges were showing up, but those were commits that I has originally pulled from your repo.

**Comment by julien-f** [comment]
LGTM, but before I merge I'd like you to squash your commits (meaning your PR should only contain one beautiful commit :) ):

```
> git checkout Dan2-conditional
> git fetch upstream # Assuming upstream is this repository
> git rebase -i upstream master
> # Then follow git instructions.
```

**Comment by Danp2** [comment]
Sorry, but I'm a novice at git and I can't seems to get your steps to execute correctly. Could I just delete this PR, recreate the branch, and then send another PR with the single commit?

**Comment by julien-f** [comment]
I did it myself in #8 :)

**Pull request closed without merging**
